<h3 ><span class="glyphicon glyphicon-home text-muted"></span>Establishment work time</h3>
<table class="table table-responsive table-hover">
    <thead>
    </th><th>id</th><th>Establishment</th><th>Opening</th><th>Break from</th><th>Break to</th><th>Closing</th><th>Weekend</th></tr>
    </thead>
    <tbody>


    <?php
    if (is_array($this->worktime) && count($this->worktime)) :
    foreach($this->worktime as $worktime) : ?>
        <tr>
		<td><?php echo $this->escape($worktime['establishment_id']) ?></td>
		<td><?php echo $this->escape($worktime['establishment']) ?></td>
 		<td><?php echo $this->escape($worktime['opening']) ?></td>
		<td><?php echo $this->escape($worktime['break_from']) ?></td>
		<td><?php echo $this->escape($worktime['break_to']) ?></td>
		<td><?php echo $this->escape($worktime['closing']) ?></td>
		<td><?php echo $this->escape($worktime['weekend']) ?></td>


        </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>