<div class="carousel slide" id="carouselshowmanymoveone">
  <div class="carousel-inner">
    <div class="item active">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#" class="thumbnail"><img src="images/6.jpg" class="img-responsive"></a></div>
    </div>
    <div class="item">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#"class="thumbnail"><img src="images/4.jpg" class="img-responsive"></a></div>
    </div>
    <div class="item">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#"class="thumbnail"><img src="images/5.jpg" class="img-responsive"></a></div>
    </div>
    <div class="item">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#"class="thumbnail"><img src="images/6.jpg" class="img-responsive"></a></div>
    </div>
    <div class="item">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#"class="thumbnail"><img src="images/4.jpg" class="img-responsive"></a></div>
    </div>
    <div class="item">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#"class="thumbnail"><img src="images/5.jpg" class="img-responsive"></a></div>
    </div>
    <div class="item">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#"class="thumbnail"><img src="images/6.jpg" class="img-responsive"></a></div>
    </div>
    <div class="item">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3"><a href="#"class="thumbnail"><img src="images/4.jpg" class="img-responsive"></a></div>
    </div>
  </div>
  <a class="left carousel-control" href="#carouselshowmanymoveone" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
  <a class="right carousel-control" href="#carouselshowmanymoveone" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
</div>

<script src="../../../../public/js/jquery-1.10.2.min.js"></script>
	<script src="../../../../public/js/bootstrap.min.js"></script>
	<script src="../../../../public/js/carusell.js"></script>