<div class="row main">
    <div class="col-lg-4 col-md-4 col-sm-6 main-block">
        <div class=" img-thumbnail">
            <div id="title1">ARCHITECTURE OF Chernivtsi</div>
            <a href="index.html"> <img src="images/superbox/1.jpg" class="img-responsive"></a>
            <p class="">Chernivtsi is a hidden pearl of Europe.</p>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 main-block">
        <div class=" img-thumbnail">
            <div id="title2">EXCURSIONS IN Chernivtsi</div>
            <a href="index.html"> <img src="images/superbox/2.jpg" class="img-responsive"></a>
            <p class="">Discover all the diversity of the city with the help of the best guides.</p>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 main-block">
        <div class=" img-thumbnail">
            <div id="title3">Cultural heritage of Chernivsti</div>
            <a href="index.html"> <img src="images/superbox/3.gif" class="img-responsive"></a>
            <p class="">For centuries, Chernivtsi existed as a multinational and multicultural city.</p>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 main-block">
        <div class=" img-thumbnail">
            <div id="title4">Histrorical Chernivtsi</div>
            <a href="index.html"> <img src="images/superbox/4.jpg" class="img-responsive"></a>
            <p class="">The territory of Chernivtsi was settled in the 12th century.</p>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 main-block">
        <div class=" img-thumbnail">
            <div id="title5">SPORT AND RECREATION</div>
            <a href="index.html"> <img src="images/superbox/5.jpg" class="img-responsive"></a>
            <p class="">Around Chernivtsi are many places and things that you must see and do</p>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 main-block">
        <div class=" img-thumbnail">
            <div id="title6">ARTS in Chernivtsi</div>
            <a href="index.html"> <img src="images/superbox/6.jpg" class="img-responsive"></a>
            <p class="">Over 100 festivals of different kind are being held in Chernivtsi every year.</p>
        </div>
    </div>

</div>
