<?php
//  echo $this->headLink()->appendStylesheet('css/bootstrap.min.css');
//  echo $this->headLink()->appendStylesheet('css/style.css');

$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>
    <?php

    echo $this->form;
    ?>
