<form action="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' => 'add'))?>"> <button class="btn btn-default">Add new type of establishment</button></form>
<h3 ><span class="glyphicon glyphicon-home text-muted"></span>Establishment types</h3>

<table class="table table-responsive table-hover">
    <thead>
    </th><th>Type</th><th>Establishment</th></tr>
    </thead>
    <tbody>
    <?php
    if (is_array($this->establishmenttype) && count($this->establishmenttype)) :

        foreach($this->establishmenttype as $establishmenttype) : ?>
            <tr>
                <td><?php echo $this->escape($establishmenttype['type']) ?></td>
                <td><?php echo $this->escape($establishmenttype['establishment']) ?></td>


                <td>


                    <a href="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' => 'edit', 'id' => $establishmenttype['id'])); ?>">edit</a>

                </td>
                <td>
                    <a href="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' => 'delete',  'id' => $this->escape($establishmenttype['id']))); ?>">delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>