<p><a href="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' => 'add')) ?>">Add new establishment type</a></p>
<table>
    <tr>
        <th>Type</th>
        <th>      </th>
        <th>Establishment</th>
    </tr>
    <?php foreach($this->establishmenttype as $establishmenttype) : ?>
        <tr>
            <td><?php echo $this->escape($establishmenttype->type) ?></td>
            <td>      </td>
			  <td><?php echo $this->escape($establishmenttype->establishment) ?></td>
<td>
                <a href="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' => 'edit', 'id' => $establishmenttype->id)); ?>">edit</a>
            </td>            
		   <td>
                <a href="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' => 'delete', 'id' => $establishmenttype->id)) ?>">delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>