<!DOCTYPE html>
<!--[if IE 6]>
    <html id="ie6" class="ie"lang="en-US">
    <![endif]-->
    <!--[if IE 7]>
    <html id="ie7"  class="ie"lang="en-US">
    <![endif]-->
    <!--[if IE 8]>
    <html id="ie8"  class="ie"lang="en-US">
    <![endif]-->
    <!--[if IE 9]>
    <html id="ie9"  class="ie"lang="en-US">
    <![endif]-->
    <!--[if gt IE 9]>
    <html class="ie"lang="en-US">
    <![endif]-->

    <!-- This doesn't work but i prefer to leave it here... maybe in the future the MS will support it... i hope... -->
    <!--[if IE 10]>
    <html id="ie10"  class="ie"lang="en-US">
    <![endif]-->


    <!--[if !IE]>
    <html lang="en-US">
    <![endif]-->

<head>
	<meta charset="utf-8">
	<title>Travel</title>

	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="../../../../public/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="../../../../public/css/style.css"/><!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>

<body>	

<?php 
echo $this->form ?>

<script src="js/jquery-1.10.2.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/carusell.js"></script>
</body>
</html>