<!-- application/layouts/scripts/layout.phtml -->

<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<html id="ie6" class="ie"lang="en-US">
<![endif]-->
<!--[if IE 7]>
<html id="ie7"  class="ie"lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html id="ie8"  class="ie"lang="en-US">
<![endif]-->
<!--[if IE 9]>
<html id="ie9"  class="ie"lang="en-US">
<![endif]-->
<!--[if gt IE 9]>
<html class="ie"lang="en-US">
<![endif]-->

<!-- This doesn't work but i prefer to leave it here... maybe in the future the MS will support it... i hope... -->
<!--[if IE 10]>
<html id="ie10"  class="ie"lang="en-US">
<![endif]-->


<!--[if !IE]>
<html lang="en-US">
<![endif]-->

<head>
    <meta charset="utf-8">
    <title>Travel</title>

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Stylesheets -->
    <?php
    //  echo $this->headLink()->appendStylesheet('css/bootstrap.min.css');
    //  echo $this->headLink()->appendStylesheet('css/style.css');

    $this->headLink()->appendStylesheet($this->baseUrl()."css/bootstrap.css")
        ->appendStylesheet($this->baseUrl("css/style.css"))
        ->appendStylesheet($this->baseUrl("css/pgwslider.css"))
        ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
    echo $this->headLink();
    $this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
        ->appendFile($this->baseUrl("js/infinitescroll.js"))
        ->appendFile("http://maps.googleapis.com/maps/api/js?key=AIzaSyCUZkf_30iE3wDjCbu0AJHJfdPo4Wd4pKM&sensor=false&libraries=places")
        ->appendFile($this->baseUrl("js/pgwslider.js"))
        ->appendFile($this->baseUrl("js/v.js"))
        ->appendFile($this->baseUrl("js/cv_guide.js"))
        ->appendFile($this->baseUrl("js/bootstrap.min.js"));
    echo $this->headScript();
    ?>

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>


<header>
    <nav class=" navbar navbar-fixed" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand " href="/"><img src="/images/logo.png" ><span>Chernivtsi city guide</span></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <form id="searchthis" action="/search" style="display:inline;" method="get">
                    <!-- Search box for blogger by Namanyay Goel //-->
                    <input id="namanyay-search-box" name="q" size="40" type="text" placeholder="Type search text here..."/>
                    <input id="namanyay-search-btn" value="Search" type="submit"/>
                </form>
                <div class="pull-right">
                    Hello, <?php
                    $role = Zend_Registry::get('role');
                    echo $role;


                    ?>. You can  <a href="<?php

                    $role = Zend_Registry::get('role');


                    if(($role == 'user') or ($role == 'admin')){
                        echo $this->url(array('controller' => 'auth', 'action' =>$action = 'logout'));
                    }else{
                        echo $this->url(array('controller' => 'auth', 'action' =>$action = 'login'));
                    }

                    ?>"><?php  echo $action
                        ?></a>?
                </div>
            </ul>
            <div class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="bar1"></span>
                <span class="bar2"></span>
                <span class="bar3"></span>
                <span class="bar4"></span>
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div class="row nav_menu">
        <div class="col-lg-8 col-lg-offset-4  col-md-8 col-md-offset-3 col-sm-8 col-sm-offset-2 collapse navbar-collapse" id="navbar-collapse-1">
            <ul id="main_manu">
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentw'), null, true)?>">Walk the city</a>

                </li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmenta'), null, true)?>">Accomodation</a>
                    <ul class="sub_menu">
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmenta'), null, true)?>" data-href="ehotels">Hotels</a>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmenta'), null, true)?>" data-href="eapartments">Apartments</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmenta'), null, true)?>" data-href="ehostels">Hostels</a></li>
                    </ul>


                </li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'))?>">Culture</a>
                    <ul class="sub_menu">
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="emonuments">Monuments</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="emuseums">Museums</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="etheatres">Theatres</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="ephilarmonic">Philarmonic</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="efairs">Fairs</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="eexhibitions">Exhibitions</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="eculturalplaces">Cultural places</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'), null, true)?>" data-href="elibraries">Libraries</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'))?>">Free time</a>
                    <ul class="sub_menu">
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'), null, true)?>" data-href="eclubs">Clubs</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'), null, true)?>" data-href="eentertaimentcentres">Entertaiment centres</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'), null, true)?>" data-href=ecinemas">Cinemas</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'), null, true)?>" data-href=esport">Sport</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'), null, true)?>" data-href=eshopping">Shopping</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'))?>">Nutrition</a>
                    <ul class="sub_menu">
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'), null, true)?>" data-href="erestaurants">Restaurants</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'), null, true)?>" data-href="ebars">Bars</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'), null, true)?>" data-href="epubs">Pubs</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'), null, true)?>" data-href="epizzerias">Pizzerias</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'), null, true)?>" data-href="ecafes">Cafes</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'), null, true)?>" data-href="ecanteens" data-toggle="tab">Canteens</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'), null, true)?>" data-href="efastfood" data-toggle="tab">Fast food</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentt'))?>">Transport</a>
                    <ul class="sub_menu">
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentt'), null, true)?>" data-href="epublictransportation">Public transportation</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentt'), null, true)?>" data-href="erailbus">Rail and bus stations</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentt'), null, true)?>" data-href="eairport">Airport</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentt'), null, true)?>" data-href="erentacar">Rent a car</a></li>
                    </ul>
                </li>
            </ul>


        </div>
        <div id="main_div">
            <a href="<?php echo $this->url(
                array('controller' => 'index'),
                'default',
                true) ?>" title="back to homepage"></a>
        </div>

    </div>

</header>

<!-- MAIN CONTENT -->
<section>

    <div class="row class="k">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'addresses', 'action' =>'index'))?>">Addresses</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' =>'index'))?>">Establishment type</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'establishments', 'action' =>'index'))?>">Establishments</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'worktime', 'action' =>'index'))?>">Work time</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'comments', 'action' =>'index'))?>">Comments</a>
                </li>

            </ul>
        </div>
    </div>
    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7">

        <?php
        echo $this->layout ()->content;
        ?>

    </div>





    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">

    </div>
    </div>

</section>



<!-------------------------------------------------------------------------------------------------------------------->
<!-- FOOTER -->
    <footer>

        <div class="container">

            <div class="footer_inf">
                <div class="col-lg-5">
                    <div ><img src="/images/foot_logo.jpg" width="72" height="90" align="left">
                        <p>Made by BEDBOU 2015  Ⓒ<br>Web master: maxeem23@gmail.com</p></div>

                        Hello, <?php
                        $role = Zend_Registry::get('role');
                        echo $role;


                        ?>. You can  <a href="<?php

                        $role = Zend_Registry::get('role');


                        if(($role == 'user') or ($role == 'admin')){
                            echo $this->url(array('controller' => 'auth', 'action' =>$action = 'logout'));
                        }else{
                            echo $this->url(array('controller' => 'auth', 'action' =>$action = 'login'));
                        }

                        ?>"><?php  echo $action
                            ?></a>?
                    </div>

                <div class="col-lg-3">

                </div>
                <div class="col-lg-4"><p> Designed by kmokod23</p></div>
            </div>
        </div>




</footer>
<!-- Modal -->

<!-------------------------------------------------------------------------------------------------------------------->



</body>
</html>