<!-- application/layouts/scripts/layout.phtml -->

<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<html id="ie6" class="ie"lang="en-US">
<![endif]-->
<!--[if IE 7]>
<html id="ie7"  class="ie"lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html id="ie8"  class="ie"lang="en-US">
<![endif]-->
<!--[if IE 9]>
<html id="ie9"  class="ie"lang="en-US">
<![endif]-->
<!--[if gt IE 9]>
<html class="ie"lang="en-US">
<![endif]-->

<!-- This doesn't work but i prefer to leave it here... maybe in the future the MS will support it... i hope... -->
<!--[if IE 10]>
<html id="ie10"  class="ie"lang="en-US">
<![endif]-->


<!--[if !IE]>
<html lang="en-US">
<![endif]-->

<head>
    <meta charset="utf-8">
    <title>Travel</title>

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Stylesheets -->
    <?php
  //  echo $this->headLink()->appendStylesheet('css/bootstrap.min.css');
  //  echo $this->headLink()->appendStylesheet('css/style.css');

    $this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
        ->appendStylesheet($this->baseUrl("css/style.css"))
        ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
    echo $this->headLink();
    $this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
        ->appendFile($this->baseUrl("js/bootstrap.min.js"));
    echo $this->headScript();
    ?>

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>


<header>
    <nav class="navbar navbar-fixed" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header col-lg-10 col-md-8 col-sm-8 col-xs-7">
                <a class="navbar-brand" href="/">Chernivtsi city guide</a>
            </div>

            <ul class="nav navbar-nav navbar-right col-lg-2 col-md-4 col-sm-4 col-xs-5">
                <form><div class="btn-group form-inline">
                        <input type="text"class="btn btn-default btn-sm" class="form-control" placeholder="Search">
                        <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-search"></span></button>
                    </div>
                </form>
            </ul>
        </div><!-- /.container-fluid -->
    </nav>
    <div class="row nav_menu">
        <div class="col-lg-12" align="center">
            <ul>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmenta'))?>">Accomodation</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'))?>">Culture</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'))?>">Free time</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'))?>">Nutrition</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentt'))?>">Transport</a></li>
            </ul>

        </div>
        <div id="main_div">
            <a href="<?php echo $this->url(
                array('controller' => 'index'),
                'default',
                true) ?>" title="back to homepage"></a>
        </div>
    </div>
    
</header>

<!-- MAIN CONTENT -->
<section>

    <div class="row class="k">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'addresses', 'action' =>'index'))?>">Addresses</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'establishmenttype', 'action' =>'index'))?>">Establishment type</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'establishments', 'action' =>'index'))?>">Establishments</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'worktime', 'action' =>'index'))?>">Work time</a>
                </li>

            </ul>
        </div>
    </div>
    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7">

        <?php
        echo $this->layout ()->content;
        // echo $this->(array('controller' => 'index', 'action' => 'index'));
        ?>

    </div>





    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">

    </div>
    </div>

</section>


<!-------------------------------------------------------------------------------------------------------------------->
<!-- FOOTER -->
<footer>

    <div class="foot inform_foot">
		  <span> Made by BEDBOU 2015<span>





    </div>
</footer>
<!-- Modal -->

<!-------------------------------------------------------------------------------------------------------------------->



</body>
</html>