<!-- application/layouts/scripts/layout.phtml -->

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <form action="<?php echo $this->url(array('controller' => 'Auth'),'default',true)?>"> <button class="btn btn-default">Enter</button></form>
    <?php
    // Применяем уже знакомый метод для проверки авторизации пользователя
    if (Zend_Auth::getInstance()->hasIdentity()) {
        $url = $this->url(array('controller'=>'auth', 'action'=>'logout'));
        // если пользователь авторизирован, показываем ему кнопку "Выход"
        echo "<a href=\"{$url}\">Выход</a>";
    }
    ?>
    <meta charset="utf-8">
	<title>CV_Guide</title>

	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

		<!-- Stylesheets -->
		<?php
		echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css');
		echo $this->headLink()->appendStylesheet('/css/style.css');
		?>

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
		<!-- Stylesheets -->


</head>
<body>

<div id="container">
    <!-------------------------------------------------------------------------------------------------------------------->
    <div id="header">
<header>
	<nav class="navbar navbar-default  navbar-fixed" role="navigation">
	  <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <a class="navbar-brand" href="/">Chernivtsi city guide</a>
		</div>
<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		  <ul class="nav navbar-nav navbar-right">
			<form><div class="btn-group form-inline">
					<input type="text"class="btn btn-default btn-sm" class="form-control" placeholder="Search">
					<button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-search"></span></button>
					</div>
						<li class="dropdown">
						   <div class="btn-group">
									   <button class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModalreg"><span class="glyphicon glyphicon-user"></span></button>

						</li></form>
		  </ul>
		</div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="col-lg-12 nav_menu">
			<ul class="nav nav-pills">
			  <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmenta'))?>">Accomodation</a></li>
			  <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentc'))?>">Culture</a></li>
			  <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentf'))?>">Free time</a></li>
			  <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentn'))?>">Nutrition</a></li>
			  <li><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishmentt'))?>">Transport</a></li>
			</ul>

 </div>
        <div id="main_div">
            <a href="<?php echo $this->url(
                array('controller' => 'index'),
                'default',
                true) ?>" title="back to homepage"></a>
        </div>

    </div>

 </header>
 </div>

 <!-- MAIN CONTENT -->
<section>

<div class="row">
    <div class="col-lg-2">

        <form action="<?php echo $this->url(array('controller' => 'Addresses'),'default',true)?>"> <button class="btn btn-default">Addresses</button></form>
        <form action="<?php echo $this->url(array('controller' => 'Establishmenttype'),'default',true)?>"> <button class="btn btn-default">Establishment type</button></form>
        <form action="<?php echo $this->url(array('controller' => 'Establishments'),'default',true)?>"> <button class="btn btn-default">Establishments</button></form>
        <form action="<?php echo $this->url(array('controller' => 'Worktime'),'default',true)?>"> <button class="btn btn-default">Work time</button></form>


        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">Walk the city
                    </a>
                </li>
                <li>
                    <a href="#">City map</a>
                </li>
                <li>
                    <a href="#">Routes</a>
                </li>
                <li>
                    <a href="#">Popular places</a>
                </li>
                <li>
                    <a href="#">Useful information</a>
                </li>

                <li>
                    <a href="#">Contacts</a>
                </li>
            </ul>
        </div>


    </div>
    <div class="col-lg-7">

            <?php
            echo $this->layout ()->content;
            // echo $this->(array('controller' => 'index', 'action' => 'index'));
            ?>

    </div>





    <div class="col-lg-3">
        <div class="popular">
            <a href="#">POPULAR </a>
            <a href="#"> RECENT </a>
            <a href="#"> RANDOM</a>
        </div>
        <ul class="media-list">
            <li class="media">
                <a href="" class="pull-left"><img src="images/8.jpg" alt="Upcoming" class="media-object "></a>
                <div class="media-body">
                    <h5 class="media-heading">Університет ім. Ю.Федьковича</h5>
                    <p class="text-muted"><small>Опубліковано 23.12.2014</small></p>


                </div>
            </li>
            <li class="media">
                <a href="" class="pull-left"><img src="images/9.jpg" alt="Upcoming" class="media-object "></a>
                <div class="media-body">
                    <h5 class="media-heading">Центральна площа</h5>
                    <p class="text-muted"><small>Опубліковано 23.12.2014</small></p>


                </div>
            </li>
            <li class="media">
                <a href="" class="pull-left"><img src="images/34.jpg" alt="Upcoming" class="media-object "></a>
                <div class="media-body">
                    <h5 class="media-heading">Турeцька площа</h5>
                    <p class="text-muted"><small>Опубліковано 23.12.2014</small></p>


                </div>
            </li>
            <li class="media">
                <a href="" class="pull-left"><img src="images/34.jpg" alt="Upcoming" class="media-object "></a>
                <div class="media-body">
                    <h5 class="media-heading">Турeцька площа</h5>
                    <p class="text-muted"><small>Опубліковано 23.12.2014</small></p>


                </div>
            </li>
            <li class="media">
                <a href="" class="pull-left"><img src="images/9.jpg" alt="Upcoming" class="media-object "></a>
                <div class="media-body">
                    <h5 class="media-heading">Центральна площа</h5>
                    <p class="text-muted"><small>Опубліковано 23.12.2014</small></p>


                </div>
            </li>
        </ul>
    </div>
</div>

</section>


<!-------------------------------------------------------------------------------------------------------------------->
   <!-- FOOTER -->
		<footer>

          <div class="foot inform_foot">
		  <span> Made by BEDBOU 2015<span>





          </div>
		</footer>
				 <!-- Modal -->
				<div class="modal fade" id="myModalreg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
					<div class="modal-content">
					  <div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                         <h3 id="myModalLabel">Hello, friend!</h3>
					  </div>
					  <div class="modal-body">
							<ul class="nav nav-tabs" id="login-or-register">
							  <li class="active"><a href="#profile" data-toggle="tab">Authorization</a></li>
							</ul>
							<div class="tab-content">

							  <div class="tab-pane active" id="profile">
									<form action="#">
									<div class="row">
											<h3>Authorize, please.</h3>
										</div>
										<div class="row">

											<label for="user_login">Enter Your login</label>
											<input id="user_login" name="login" value="" />
										</div>
										<div class="row">
											<label for="user_password">Enter Your password</label>
											<input id="user_password" name="password" value="" />
										</div>
										<div class="row">
									   <input type="checkbox" id="remember-me" /><label for="remember-me">Remember me?</label>
									   </div>
										<div class="row">
											<input type="submit" id="login_button" class="login_button" value="Вхід" />
										</div>
									</form>
							  </div>
							</div>
						  </div>


					  </div>
					  <div class="modal-footer">
						 <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					  </div>
					</div>
				  </div>
    <!-------------------------------------------------------------------------------------------------------------------->

<script src="js/jquery-1.10.2.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/carusell.js"></script>
</body>
</html>