<?php
$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
   ->appendFile($this->baseUrl("js/googlemaps/googlemaps.js"))
   ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >


        <div>
            <table class="table table-responsive table-hover">
                <?php if (is_array($this->establishments) && count($this->establishments)) :
                //foreach($this->establishments as $establishments) :
                ?>
                <ul class="list-unstyled detail" data-gps="<?php echo $this->escape($this->establishments['gps']) ?>" data-address="<?php echo $this->escape($this->establishments['town']), " ", $this->escape($this->establishments['address'])," ", $this->escape($this->establishments['build']); ?>">


                    <li>
                        <article>
                            <div class="media">
                                <h3 class="media-heading media_top"><?php echo $this->escape($this->establishments['establishment']) ?> <?php echo $this->escape($this->establishments['title']) ?></h3>
                                <div class="line"></div>
                                <a class="pull-left images_size_descr"><img src="/images/<?php echo $this->escape($this->establishments['image'])?>" alt="Image" class="media-object"></a>

                                <div class="media-body">
                                    <address>

                                        <span>Telefone:</span>+1 800 603 6035<br>
                                        <span>Address:</span>3 Katedralna sqr. <br>
                                        <span> E-mail:</span> <a href="#">mail@demolink.org</a><br>
                                        <span>Work time</span> 08:00 - 22:00<br>
                                    </address>
<!--                                    <address>-->
<!--                                        <span>Address:</span> --><?php //echo $this->escape($this->establishments['build']) ?><!--, --><?php //echo $this->escape($this->establishments['address'])?><!-- St.<br>-->
<!--                                        <span>Telephone:</span>+38 --><?php //echo $this->escape($this->establishments['telephone'])?><!--<br>-->
<!--                                        <span>Work time:</span> --><?php //echo $this->escape($this->establishments['opening'])?><!-- - --><?php //echo $this->escape($this->establishments['closing'])?><!--<br>-->
<!--                                    </address>-->
                                </div> <!-- end media-body -->

                            </div> <!-- end media -->
                            <div class="line"></div>
                        </article>
                        <p><?php echo $this->escape($this->establishments['description'])?></p>
                        <div class="line"></div>
                        <div id="map-canvas" style="width:650px; height:300px"></div>
                        <div class="line"></div>
                    </li>
                    <?php //endforeach; ?>
                    <?php endif;
                    ?>
            </table>


        </div>
    </div>
