<?php
$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/infinitescroll.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >
    <h3><span class="glyphicon glyphicon-home text-muted"></span>Where to stay</h3>
    <ul class="nav nav-tabs menu1 establishmentloading">
        <li><a href="eclubs" data-toggle="tab">Clubs</a></li>
        <li><a href="eentertaimentcentres" data-toggle="tab">Entertaiment centres</a></li>
        <li><a href="ecinemas" data-toggle="tab">Cinemas</a></li>
        <li><a href="esport" data-toggle="tab">Sport</a></li>
        <li><a href="eshopping" data-toggle="tab">Shopping</a></li>
    </ul>
    <div class="estcontent">

    </div>

</div>