<?php
$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/infinitescroll.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >
    <h3><span class="glyphicon glyphicon-home text-muted"></span>City transportation</h3>
    <ul class="nav nav-tabs menu1 establishmentloading">
        <li><a href="epublictransportation" data-toggle="tab">Public transportation</a></li>
        <li><a href="erailbus" data-toggle="tab">Rail and bus stations</a></li>
        <li><a href="eairport" data-toggle="tab">Airport</a></li>
        <li><a href="erentacar" data-toggle="tab">Rent a car</a></li>

    </ul>
    <div class="estcontent">

    </div>

</div>