<?php
$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/infinitescroll.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >

    <ul class="nav nav-tabs menu1 establishmentloading">
        <li><a href="ehotels">Hotel</a></li>
        <li><a href="emotels" data-toggle="tab">Motel</a></li>
        <li><a href="eapartments" data-toggle="tab">Apartment</a></li>
        <li><a href="ehostels" data-toggle="tab">Hostel</a></li>
    </ul>
    <div class="estcontent">

    </div>

</div>








