<?php
//  echo $this->headLink()->appendStylesheet('css/bootstrap.min.css');
//  echo $this->headLink()->appendStylesheet('css/style.css');

$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >
<div class="menu1">
<br id="tab2"/><br id="tab3"/><br id="tab4"/><br id="tab5"/>
<a href="#tab1">Railway station</a><a href="#tab2">Bus station</a><a href="#tab3">Airport</a><a href="#tab4">Public transportation</a><a href="#tab5">Rent a car</a>
<div>
    <h3 ><span class="glyphicon glyphicon-home text-muted"></span>Railway stations</h3>
    <table class="table table-responsive table-hover">
        <thead>
        <tr><th></th><th>Title</th><th>Address</th><th>Telephone</th></tr>
        </thead>
        <tbody>
        <?php
        if (is_array($this->establishments) && count($this->establishments)) :
            foreach($this->establishments as $establishments) :
                //  print_r($establishments);
                ?>
                <tr class="clickable success" data-toggle="collapse" id="row<?php  echo $this->escape($establishments['id']) ?>" data-target=".row<?php echo $this->escape($establishments['id'])?>">
                    <td><i class="glyphicon glyphicon-plus"></i></td>

                    <td><?php echo $this->escape($establishments['establishment']) ?>: <?php echo $this->escape($establishments['title']) ?></td>
                    <td>c. <?php echo $this->escape($establishments['town']) ?>, <?php echo $this->escape($establishments['address']) ?> st., <?php echo $this->escape($establishments['build']) ?></td>

                    <td><span class="glyphicon glyphicon-earphone text-muted"></span >+380<?php echo $this->escape($establishments['telephone']) ?></td>
                </tr>


                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td colspan="4"><b>Description:</b><?php echo $this->escape($establishments['description']) ?></td>
                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>GPS:</td>
                    <td><?php echo $this->escape($establishments['gps']) ?></td>



                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Work time:</td>
                    <td><?php echo $this->escape($establishments['opening']) ?> - <?php echo $this->escape($establishments['closing']) ?></td>

                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Break:</td>
                    <td><?php echo $this->escape($establishments['break_from']) ?> - <?php echo $this->escape($establishments['break_to']) ?></td>


                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Weekend:</td>
                    <td><?php echo $this->escape($establishments['weekend']) ?></td>

                </tr>


            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>

</div>
<div>
    <h3 ><span class="glyphicon glyphicon-home text-muted"></span>Bus stations</h3>
    <table class="table table-responsive table-hover">
        <thead>
        <tr><th></th><th>Title</th><th>Address</th><th>Telephone</th></tr>
        </thead>
        <tbody>
        <?php
        if (is_array($this->establishments) && count($this->establishments)) :
            foreach($this->establishments as $establishments) :
                //  print_r($establishments);
                ?>
                <tr class="clickable success" data-toggle="collapse" id="row<?php  echo $this->escape($establishments['id']) ?>" data-target=".row<?php echo $this->escape($establishments['id'])?>">
                    <td><i class="glyphicon glyphicon-plus"></i></td>

                    <td><?php echo $this->escape($establishments['establishment']) ?>: <?php echo $this->escape($establishments['title']) ?></td>
                    <td>c. <?php echo $this->escape($establishments['town']) ?>, <?php echo $this->escape($establishments['address']) ?> st., <?php echo $this->escape($establishments['build']) ?></td>

                    <td><span class="glyphicon glyphicon-earphone text-muted"></span >+380<?php echo $this->escape($establishments['telephone']) ?></td>
                </tr>


                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td colspan="4"><b>Description:</b><?php echo $this->escape($establishments['description']) ?></td>
                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>GPS:</td>
                    <td><?php echo $this->escape($establishments['gps']) ?></td>



                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Work time:</td>
                    <td><?php echo $this->escape($establishments['opening']) ?> - <?php echo $this->escape($establishments['closing']) ?></td>

                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Break:</td>
                    <td><?php echo $this->escape($establishments['break_from']) ?> - <?php echo $this->escape($establishments['break_to']) ?></td>


                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Weekend:</td>
                    <td><?php echo $this->escape($establishments['weekend']) ?></td>

                </tr>


            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>

</div>
<div>
    <h3 ><span class="glyphicon glyphicon-home text-muted"></span>Airport</h3>
    <table class="table table-responsive table-hover">
        <thead>
        <tr><th></th><th>Title</th><th>Address</th><th>Telephone</th></tr>
        </thead>
        <tbody>
        <?php
        if (is_array($this->establishments) && count($this->establishments)) :
            foreach($this->establishments as $establishments) :
                //  print_r($establishments);
                ?>
                <tr class="clickable success" data-toggle="collapse" id="row<?php  echo $this->escape($establishments['id']) ?>" data-target=".row<?php echo $this->escape($establishments['id'])?>">
                    <td><i class="glyphicon glyphicon-plus"></i></td>

                    <td><?php echo $this->escape($establishments['establishment']) ?>: <?php echo $this->escape($establishments['title']) ?></td>
                    <td>c. <?php echo $this->escape($establishments['town']) ?>, <?php echo $this->escape($establishments['address']) ?> st., <?php echo $this->escape($establishments['build']) ?></td>

                    <td><span class="glyphicon glyphicon-earphone text-muted"></span >+380<?php echo $this->escape($establishments['telephone']) ?></td>
                </tr>


                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td colspan="4"><b>Description:</b><?php echo $this->escape($establishments['description']) ?></td>
                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>GPS:</td>
                    <td><?php echo $this->escape($establishments['gps']) ?></td>



                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Work time:</td>
                    <td><?php echo $this->escape($establishments['opening']) ?> - <?php echo $this->escape($establishments['closing']) ?></td>

                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Break:</td>
                    <td><?php echo $this->escape($establishments['break_from']) ?> - <?php echo $this->escape($establishments['break_to']) ?></td>


                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Weekend:</td>
                    <td><?php echo $this->escape($establishments['weekend']) ?></td>

                </tr>


            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>

</div>
<div>
    <h3 ><span class="glyphicon glyphicon-home text-muted"></span>Public transportation</h3>
    <table class="table table-responsive table-hover">
        <thead>
        <tr><th></th><th>Title</th><th>Address</th><th>Telephone</th></tr>
        </thead>
        <tbody>
        <?php
        if (is_array($this->establishments) && count($this->establishments)) :
            foreach($this->establishments as $establishments) :
                //  print_r($establishments);
                ?>
                <tr class="clickable success" data-toggle="collapse" id="row<?php  echo $this->escape($establishments['id']) ?>" data-target=".row<?php echo $this->escape($establishments['id'])?>">
                    <td><i class="glyphicon glyphicon-plus"></i></td>

                    <td><?php echo $this->escape($establishments['establishment']) ?>: <?php echo $this->escape($establishments['title']) ?></td>
                    <td>c. <?php echo $this->escape($establishments['town']) ?>, <?php echo $this->escape($establishments['address']) ?> st., <?php echo $this->escape($establishments['build']) ?></td>

                    <td><span class="glyphicon glyphicon-earphone text-muted"></span >+380<?php echo $this->escape($establishments['telephone']) ?></td>
                </tr>


                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td colspan="4"><b>Description:</b><?php echo $this->escape($establishments['description']) ?></td>
                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>GPS:</td>
                    <td><?php echo $this->escape($establishments['gps']) ?></td>



                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Work time:</td>
                    <td><?php echo $this->escape($establishments['opening']) ?> - <?php echo $this->escape($establishments['closing']) ?></td>

                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Break:</td>
                    <td><?php echo $this->escape($establishments['break_from']) ?> - <?php echo $this->escape($establishments['break_to']) ?></td>


                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Weekend:</td>
                    <td><?php echo $this->escape($establishments['weekend']) ?></td>

                </tr>


            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>

</div>

<div>
    <h3 ><span class="glyphicon glyphicon-home text-muted"></span>Rent a car</h3>
    <table class="table table-responsive table-hover">
        <thead>
        <tr><th></th><th>Title</th><th>Address</th><th>Telephone</th></tr>
        </thead>
        <tbody>
        <?php
        if (is_array($this->establishments) && count($this->establishments)) :
            foreach($this->establishments as $establishments) :
                //  print_r($establishments);
                ?>
                <tr class="clickable success" data-toggle="collapse" id="row<?php  echo $this->escape($establishments['id']) ?>" data-target=".row<?php echo $this->escape($establishments['id'])?>">
                    <td><i class="glyphicon glyphicon-plus"></i></td>

                    <td><?php echo $this->escape($establishments['establishment']) ?>: <?php echo $this->escape($establishments['title']) ?></td>
                    <td>c. <?php echo $this->escape($establishments['town']) ?>, <?php echo $this->escape($establishments['address']) ?> st., <?php echo $this->escape($establishments['build']) ?></td>

                    <td><span class="glyphicon glyphicon-earphone text-muted"></span >+380<?php echo $this->escape($establishments['telephone']) ?></td>
                </tr>


                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td colspan="4"><b>Description:</b><?php echo $this->escape($establishments['description']) ?></td>
                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>GPS:</td>
                    <td><?php echo $this->escape($establishments['gps']) ?></td>



                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Work time:</td>
                    <td><?php echo $this->escape($establishments['opening']) ?> - <?php echo $this->escape($establishments['closing']) ?></td>

                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Break:</td>
                    <td><?php echo $this->escape($establishments['break_from']) ?> - <?php echo $this->escape($establishments['break_to']) ?></td>


                </tr>
                <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                    <td class="suc"><b>Weekend:</td>
                    <td><?php echo $this->escape($establishments['weekend']) ?></td>

                </tr>


            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>

</div>
</div>
</div>








