<?php
$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/infinitescroll.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >
    <h3><span class="glyphicon glyphicon-home text-muted"></span>What to visit</h3>
    <ul class="nav nav-tabs menu1 establishmentloading">
        <li><a href="emonuments" data-toggle="tab">Monuments</a></li>
        <li><a href="emuseums" data-toggle="tab">Museums</a></li>
        <li><a href="etheatres" data-toggle="tab">Theatres</a></li>
        <li><a href="ephilarmonic" data-toggle="tab">Philarmonic</a></li>
        <li><a href="efairs" data-toggle="tab">Fairs</a></li>
        <li><a href="eexhibitions" data-toggle="tab">Exhibitions</a></li>
        <li><a href="eculturalplaces" data-toggle="tab">Cultural places</a></li>
        <li><a href="elibraries" data-toggle="tab">Libraries</a></li>
    </ul>
    <div class="estcontent">

    </div>

</div>