<?php
$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/infinitescroll.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >
    <h3><span class="glyphicon glyphicon-home text-muted"></span>Where to eat out</h3>
    <ul class="nav nav-tabs menu1 establishmentloading">
        <li><a href="erestaurants" data-toggle="tab">Restaurants</a></li>
        <li><a href="ebars" data-toggle="tab">Bars</a></li>
        <li><a href="epubs" data-toggle="tab">Pubs</a></li>
        <li><a href="epizzerias" data-toggle="tab">Pizzerias</a></li>
        <li><a href="ecafes" data-toggle="tab">Cafes</a></li>
        <li><a href="ecanteens" data-toggle="tab">Canteens</a></li>
        <li><a href="efastfood" data-toggle="tab">Fast food</a></li>
    </ul>
    <div class="estcontent">

    </div>

</div>