<?php
$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/infinitescroll.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<div class="row" >
    <h3><span class="glyphicon glyphicon-home text-muted"></span>Where to stay</h3>
    <ul class="nav nav-tabs menu1 establishmentloading">
        <li><a href="ehotels">Hotels</a></li>
        <li><a href="eapartments" data-toggle="tab">Apartments</a></li>
        <li><a href="ehostels" data-toggle="tab">Hostels</a></li>
    </ul>
    <div class="estcontent">

    </div>

</div>








