<?php
//  echo $this->headLink()->appendStylesheet('css/bootstrap.min.css');
//  echo $this->headLink()->appendStylesheet('css/style.css');

$this->headLink()->appendStylesheet($this->baseUrl("css/bootstrap.css"))
    ->appendStylesheet($this->baseUrl("css/style.css"))
    ->appendStylesheet($this->baseUrl("css/bootstrap.min.css"));
echo $this->headLink();
$this->headScript()->appendFile($this->baseUrl("js/jquery-1.10.2.min.js"))
    ->appendFile($this->baseUrl("js/bootstrap.min.js"));
echo $this->headScript();
?>

<table class="table table-responsive table-hover">
    <thead>
    <tr><th>id</th><th>Title</th><th>Address</th><th>Telephone</th></tr>
    </thead>
    <tbody>
    <?php
    if (is_array($this->establishments) && count($this->establishments)) :
        foreach($this->establishments as $establishments) :
             // print_r($establishment);
            ?>

            <td><?php  echo $this->escape($establishments['id']) ?></td>
            <td> <?php echo $this->escape($establishments['title']) ?></td>
            <td> <?php echo $this->escape($establishments['address']) ?> </td>
            <td> <?php echo $this->escape($establishments['telephone']) ?> </td>

        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>