<p><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'add')) ?>">Add new establishment</a></p>
<table>
    <tr>
        <th>Title</th>
        <th>      </th>
        <th>Address</th>
		<th>      </th>
        <th>GPS</th>
		<th>      </th>
        <th>Telephone</th>
		<th>      </th>
        <th>Description</th>
    </tr>
    <?php 
	foreach($this->establishments as $establishments) :
	
	?>
        <tr>
            <td><?php echo $this->escape($establishments->title) ?></td>
            <td>      </td>
			  <td><?php echo $this->escape($establishments->street) ?></td>
			  <td>      </td>
			  <td><?php echo $this->escape($establishments->gps) ?></td>
			   <td>      </td>
			  <td><?php echo $this->escape($establishments->telephone) ?></td>
			     <td>      </td>
			  <td><?php echo $this->escape($establishments->description) ?></td>
			<td>
                <a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'edit', 'id' => $establishments->id)); ?>">edit</a>
            </td>           
		   <td>
                <a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'delete', 'id' => $establishments->id));?>">delete</a>
            </td>
        
		</tr>
	
    <?php endforeach; ?>
</table>