<p>Are you sure, that you want to delete:
    '<?php echo $this->escape($this->addresses['street']); ?>' ?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->comments['id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="ex" value="No" />
    </div>
</form>