
<h3 ><span class="glyphicon glyphicon-home text-muted"></span>Comments</h3>

<table class="table table-responsive table-hover">
    <thead>
    </th><th>id</th><th>Establishment</th><th>Username</th><th>Comment</th><th>Date</th></tr>
    </thead>
    <tbody>
    <?php
    if (is_array($this->comments) && count($this->comments)) :

        foreach($this->comments as $comments) : ?>
            <tr>
                <td><?php echo $this->escape($comments['id']) ?></td>
                <td><?php echo $this->escape($comments['establishment']) ?></td>
                <td><?php echo $this->escape($comments['username']) ?></td>
                <td><?php echo $this->escape($comments['comment']) ?></td>
                <td><?php echo $this->escape($comments['date']) ?></td>
           
                <td>
                    <a href="<?php echo $this->url(array('controller' => 'comments', 'action' => 'delete',  'id' => $this->escape($comments['id']))); ?>">delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>