<ul class="nav nav-tabs pull-center">
    <li onclick="open<?php echo $this->escape($establishments['types']) ?>"><a>Hotel</a><table class="table table-responsive table-hover">
            <thead>
            <tr><th></th><th>Title</th><th>Address</th><th>Telephone</th></tr>
            </thead>
            <tbody>
            <?php
            if (is_array($this->establishments) && count($this->establishments)) :
                foreach($this->establishments as $establishments) :
                    //  print_r($establishments);
                    ?>
                    <tr class="clickable success" data-toggle="collapse" id="row<?php  echo $this->escape($establishments['id']) ?>" data-target=".row<?php echo $this->escape($establishments['id'])?>">
                        <td><i class="glyphicon glyphicon-plus"></i></td>

                        <td><?php echo $this->escape($establishments['establishment']) ?>: <?php echo $this->escape($establishments['title']) ?></td>
                        <td>c. <?php echo $this->escape($establishments['town']) ?>, <?php echo $this->escape($establishments['address']) ?> st., <?php echo $this->escape($establishments['build']) ?></td>

                        <td><span class="glyphicon glyphicon-earphone text-muted"></span >+380<?php echo $this->escape($establishments['telephone']) ?></td>
                    </tr>


                    <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                        <td colspan="4"><b>Description:</b><?php echo $this->escape($establishments['description']) ?></td>
                    </tr>
                    <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                        <td class="suc"><b>GPS:</td>
                        <td><?php echo $this->escape($establishments['gps']) ?></td>



                    </tr>
                    <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                        <td class="suc"><b>Work time:</td>
                        <td><?php echo $this->escape($establishments['opening']) ?> - <?php echo $this->escape($establishments['closing']) ?></td>

                    </tr>
                    <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                        <td class="suc"><b>Break:</td>
                        <td><?php echo $this->escape($establishments['break_from']) ?> - <?php echo $this->escape($establishments['break_to']) ?></td>


                    </tr>
                    <tr class="collapse row<?php echo $this->escape($establishments['id']) ?>">
                        <td class="suc"><b>Weekend:</td>
                        <td><?php echo $this->escape($establishments['weekend']) ?></td>

                    </tr>


                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </li>
    <li><a >Motel</a></li>
    <li><a >Apartment</a></li>
    <li><a href="#">Hostel</a></li>
</ul>
<h3 ><span class="glyphicon glyphicon-home text-muted"></span>Establishments</h3>









