<?php if ($this->pageCount): ?>
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
        <a href="<?php echo $this->url(array('page' => $this->first,'query' =>  $this->query)) ?>">
            First
        </a> |
    <?php else: ?>
        <span class="disabled">First</span> |
    <?php endif; ?>

    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <a href="<?php echo $this->url(array('page' => $this->previous,'query' =>  $this->query)) ?>">
            &lt; Previous
        </a> |
    <?php else: ?>
        <span class="disabled">&lt; Previous</span> |
    <?php endif; ?>
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <a href="<?php echo $this->url(array('page' => $this->next,'query' =>  $this->query)); ?>">
            Next &gt;
        </a> |
    <?php else: ?>
        <span class="disabled">Next &gt;</span> |
    <?php endif; ?>
    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
        <a href="<?php echo $this->url(array('page' => $this->last, 'query' =>  $this->query ));?>">
            Last
        </a>
    <?php else: ?>
        <span class="disabled">Last</span>
    <?php endif; ?>

    </div>
<?php endif; ?>