<?php

echo $this->headLink()->appendStylesheet('../../../../public/css/bootstrap.min.css');
echo $this->headLink()->appendStylesheet('../../../../public/css/style.css');

?>


<?php if(empty($this->hits)) : ?>
   <div>
       No results were found
   </div>
<?php else:
echo "<ul class='list-unstyled'>";
foreach($this->paginator as $hit) :
?>
    <ul class="list-unstyled">
        <li>
            <article>
                <div class="media media_top">
                    <a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishment',  'id' => $this->escape($hit->id)), null, true)?>" class="pull-left images_size"><img src="/images/<?php
                        $images = explode(",",$this->escape($hit->image));
                        echo $images[0]; ?>" alt="Image" class="media-object"></a>
                    <div class="media-body">
                        <h4 class="media-heading"><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishment',  'id' => $this->escape($hit->id)), null, true)?>"><?php echo $this->escape($hit->establishment) ?>: <?php echo $this->escape($hit->title) ?></a></h4>
                        <ul class="list-inline description">
                            <li><?php echo $this->escape($hit->description) ?> </li><br>
                            <li class="address_str"><a href="<?php echo $this->url(array('controller' => 'establishments', 'action' => 'establishment',  'id' => $this->escape($hit->id)), null, true)?>"><?php echo $this->escape($hit->build) ?> <?php echo $this->escape($hit->address) ?></a></li>
                        </ul>

                    </div> <!-- end media-body -->
                </div> <!-- end media -->
            </article>
            <div class="line"></div>
        </li>
    </ul>
<?php endforeach; ?>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
    'Sliding',
    'search/controls.phtml', array(
        'query' => $this->query) );  ?>