<tr>
	<td><?php echo $this->escape($this->title);?></td>
	<td><?php echo $this->escape($this->street);?></td>
	<td><?php echo $this->escape($this->gps);?></td>
	<td><?php echo $this->escape($this->telephone);?></td>
	<td><?php echo $this->escape($this->description);?></td>
	<td><a
		href="<?php echo $this->url(array('controller'=>'establishments', 'action'=>'edit', 'id'=>$this->id));?>"><i
			class='icon-pencil'></i></a></td>
	<td><a class='confirm del'
		href="<?php echo $this->url(array('controller'=>'establishments', 'action'=>'delete', 'id'=>$this->id));?>"><i
			class='icon-trash'></i></a></td>
</tr>